package view;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import config.Config;
import controller.MainController;
import java.awt.Component;
import view.StudentView;
import view.ReportCardView;
import view.ClassView;

/**
 *
 * @author sidneyferracinjr
 */
public class MainView extends javax.swing.JFrame {
    
    private final MainController mainController = new MainController(this);
    private final Config config = Config.getInstance();
    private String directoryPath;
    
    /**
     * Creates new form JPrincipal
     */
    public MainView() {
        initComponents();
        this.directoryPath = !tfDirectoryPath.getText().isBlank() ? tfDirectoryPath.getText() : config.getProperty("directoryPath");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDirectoryPath = new javax.swing.JLabel();
        tfDirectoryPath = new javax.swing.JTextField();
        btnSelectDirectory = new javax.swing.JButton();
        spSelectedDirectory = new javax.swing.JScrollPane();
        taSelectedDirectory = new javax.swing.JTextArea();
        lblSelectedDirectory = new javax.swing.JLabel();
        btnStudent = new javax.swing.JButton();
        btnReportCard = new javax.swing.JButton();
        btnClass = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidade Federal do Brasil");

        lblDirectoryPath.setText("Salvar Arquivos em...");

        tfDirectoryPath.setToolTipText("");

        btnSelectDirectory.setText("Selecionar");
        btnSelectDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectDirectoryActionPerformed(evt);
            }
        });

        taSelectedDirectory.setColumns(20);
        taSelectedDirectory.setRows(5);
        spSelectedDirectory.setViewportView(taSelectedDirectory);

        lblSelectedDirectory.setText("Pasta Selecionada");

        btnStudent.setText("Aluno");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnReportCard.setText("Boletim");
        btnReportCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportCardActionPerformed(evt);
            }
        });

        btnClass.setText("Turma");
        btnClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectedDirectory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectDirectory))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfDirectoryPath)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spSelectedDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDirectoryPath))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClass)
                    .addComponent(btnStudent)
                    .addComponent(btnReportCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDirectoryPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDirectoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelectDirectory)
                    .addComponent(lblSelectedDirectory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSelectedDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        openStudentView();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnReportCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportCardActionPerformed
        openReportCardView();
    }//GEN-LAST:event_btnReportCardActionPerformed

    private void btnClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassActionPerformed
        openClassView();
    }//GEN-LAST:event_btnClassActionPerformed

    private void btnSelectDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectDirectoryActionPerformed
        try {
            selectDirectory();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectDirectoryActionPerformed

    private void openStudentView() {
        StudentView studentView = new StudentView(tfDirectoryPath.getText());
        studentView.setVisible(true);
    }
    
    private void openReportCardView() {
        ReportCardView reportCardView = new ReportCardView();
        reportCardView.setVisible(true);
    }
    
    private void openClassView() {
        ClassView classView = new ClassView();
        classView.setVisible(true);
    }
    
    private void selectDirectory() throws IOException {
        directoryPath = mainController.selectDirectory(tfDirectoryPath.getText());
        
        if (directoryPath == null) {
            showMessage(null, "O caminho da pasta não pode ser vazio.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            describeDirectory(mainController.describeDirectory(directoryPath));
            tfDirectoryPath.setText(directoryPath);
        }
    }
    
    private void describeDirectory(String selectedDirectory) {
        if (taSelectedDirectory == null) {
            taSelectedDirectory = new JTextArea();
            taSelectedDirectory.setEditable(false);
            taSelectedDirectory.setLineWrap(true);
            taSelectedDirectory.setWrapStyleWord(true);

            spSelectedDirectory = new JScrollPane(taSelectedDirectory);
            add(spSelectedDirectory);
        }

        taSelectedDirectory.setText(selectedDirectory);

        validate();
        repaint();
    }
    
    public void showMessage(Component parentComponent, Object message, String title, int messageType) {
        JOptionPane.showMessageDialog(parentComponent, message, title, messageType);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClass;
    private javax.swing.JButton btnReportCard;
    private javax.swing.JButton btnSelectDirectory;
    private javax.swing.JButton btnStudent;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDirectoryPath;
    private javax.swing.JLabel lblSelectedDirectory;
    private javax.swing.JScrollPane spSelectedDirectory;
    private javax.swing.JTextArea taSelectedDirectory;
    private javax.swing.JTextField tfDirectoryPath;
    // End of variables declaration//GEN-END:variables
}
