/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.Config;
import java.util.Map;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import controller.PrincipalController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.AlunoView;
import view.BoletimView;
import view.TurmaView;

/**
 *
 * @author sidneyferracinjr
 */
public class PrincipalView extends javax.swing.JFrame {
    
    PrincipalController principalController = new PrincipalController();
    Config config = Config.getInstance();
    String filePath;
    /**
     * Creates new form JPrincipal
     */
    public PrincipalView() {
        initComponents();
        this.filePath = tfSalvarEm.getText().isBlank() ? config.getProperty("filePath") : tfSalvarEm.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfSalvarEm = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        spPastaSelecionada = new javax.swing.JScrollPane();
        taPastaSelecionada = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnAluno = new javax.swing.JButton();
        btnBoletim = new javax.swing.JButton();
        btnTurma = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidade Federal do Brasil");

        jLabel1.setText("Salvar Arquivos em...");

        tfSalvarEm.setToolTipText("");

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        taPastaSelecionada.setColumns(20);
        taPastaSelecionada.setRows(5);
        spPastaSelecionada.setViewportView(taPastaSelecionada);

        jLabel2.setText("Pasta Selecionada");

        btnAluno.setText("Aluno");
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });

        btnBoletim.setText("Boletim");
        btnBoletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletimActionPerformed(evt);
            }
        });

        btnTurma.setText("Turma");
        btnTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurmaActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spPastaSelecionada)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelecionar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBoletim, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfSalvarEm))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTurma)
                    .addComponent(btnAluno)
                    .addComponent(btnBoletim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSalvarEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelecionar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPastaSelecionada, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        abrirJAluno();
    }//GEN-LAST:event_btnAlunoActionPerformed

    private void btnBoletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletimActionPerformed
        abrirJBoletim();
    }//GEN-LAST:event_btnBoletimActionPerformed

    private void btnTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurmaActionPerformed
        abrirJTurma();
    }//GEN-LAST:event_btnTurmaActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        try {
            selecionarDiretorio();
        } catch (IOException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void abrirJAluno() {
        AlunoView jAluno = new AlunoView(tfSalvarEm.getText());
        jAluno.setVisible(true);
    }
    
    private void abrirJBoletim() {
        BoletimView jBoletim = new BoletimView();
        jBoletim.setVisible(true);
    }
    
    private void abrirJTurma() {
        TurmaView jTurma = new TurmaView();
        jTurma.setVisible(true);
    }
    
    private void selecionarDiretorio() throws IOException {
        exibirPropriedades(principalController.salvarEm(filePath));
//        Map<String, String> propriedades = principalController.salvarEm(tfSalvarEm.getText());
//        listarPropriedades(propriedades);
//        tfSalvarEm.setText(propriedades.get("Local"));
    }
    
    private void exibirPropriedades(String conteudoTextArea){
        taPastaSelecionada = new JTextArea();
        taPastaSelecionada.setEditable(false);
        taPastaSelecionada.setLineWrap(true);
        taPastaSelecionada.setWrapStyleWord(true);
        
        spPastaSelecionada = new JScrollPane(taPastaSelecionada);
        
        if (taPastaSelecionada != null) {
            remove(taPastaSelecionada);
            remove(spPastaSelecionada);
        }
        
        add(spPastaSelecionada);
        spPastaSelecionada.setBounds(spPastaSelecionada.getBounds());
        validate();
        
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnBoletim;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane spPastaSelecionada;
    private javax.swing.JTextArea taPastaSelecionada;
    private javax.swing.JTextField tfSalvarEm;
    // End of variables declaration//GEN-END:variables
}
